LAMovies_NET6/Controllers/ActorController.cs
using LAMovies_NET6.Interfaces;
using LAMovies_NET6.Models;
using LAMovies_NET6.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace LAMovies_NET6.Controllers
{
    public class ActorController : Controller
    {
        private readonly IActorRepository _actorRepository;
        public ActorController(IActorRepository actorRepository)
        {
            _actorRepository = actorRepository;
        }
        [Authorize(Roles = "admin")]
        public IActionResult QLActor()
        {
            var genre = _actorRepository.GetActorsList();
            return View(genre);
        }
        [Authorize(Roles = "admin")]
        public IActionResult AddActor()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public IActionResult AddActor(Actor model)
        {
            if (!ModelState.IsValid)
            {
                _actorRepository.Add(model);
                return Redirect("QLActor");
            }
            else
            {
                TempData["msg"] = "Error on server side";
                return View("add", model);
            }
        }
        [Authorize(Roles = "admin")]
        public IActionResult EditActor(int id)
        {
            var data = _actorRepository.GetById(id);
            return View(data);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public IActionResult EditActor(Actor model)
        {
            if (!ModelState.IsValid)
            {
                _actorRepository.Update(model);
                return Redirect("../QLActor");
            }
            else
            {
                TempData["msg"] = "Error on server side";
                return View(model);
            }
        }
        [Authorize(Roles = "admin")]
        public IActionResult DeleteActor(int id)
        {
            var result = _actorRepository.Delete(id);
            return RedirectToAction(nameof(QLActor));
        }
        public IActionResult ListMovieByActor(string name)
        {
            var item = _actorRepository.GetActorByName(name);
            ViewData["actor"]= item;
            var listMovie = _actorRepository.GetMoviesByActor(item.idActor);
            return View(listMovie);
        }

        [Authorize(Roles = "admin")]
        public IActionResult ShowListActor(int id)
        {
            var listMovie = _actorRepository.GetMoviesByActor(id);
            var actor = _actorRepository.GetById(id);
            ViewBag.nameActor = actor.nameActor;
            return View(listMovie);
        }
    }
}

LAMovies_NET6/Controllers/GenreController.cs
using LAMovies_NET6.Interfaces;
using LAMovies_NET6.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace LAMovies_NET6.Controllers
{
    public class GenreController : Controller
    {
        private readonly IGenreRepository _genreRepository;
        public GenreController(IGenreRepository genreRepository)
        {
            _genreRepository = genreRepository;
        }
        [Authorize(Roles = "admin")]
        public IActionResult AddGenre()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public IActionResult AddGenre(Genre model)
        {
            if (!ModelState.IsValid)
            {
                _genreRepository.Add(model);
                return Redirect("QLGenres");
            }
            else
            {
                TempData["msg"] = "Error on server side";
                return View("add", model);
            }
        }

        [Authorize(Roles = "admin")]
        public IActionResult EditGenre(int id)
        {
            var data = _genreRepository.GetById(id);
            return View(data);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public IActionResult EditGenre(Genre model)
        {
            if (!ModelState.IsValid)
            {
                _genreRepository.Update(model);
                return Redirect("../QLGenres");
            }
            else
            {
                TempData["msg"] = "Error on server side";
                return View(model);
            }
        }

        [Authorize(Roles = "admin")]
        public IActionResult QLGenres()
        {
            var genre = _genreRepository.GetGenresList();
            return View(genre);
        }

        [Authorize(Roles = "admin")]
        public IActionResult DeleteGenre(int id)
        {
            var result = _genreRepository.Delete(id);
            return RedirectToAction(nameof(QLGenres));
        }
        [Authorize(Roles = "admin")]
        public IActionResult ShowList(int id)
        {
            var listMovie = _genreRepository.GetMoviesByGenres(id);
            var genre = _genreRepository.GetById(id);
            ViewBag.nameGenre = genre.nameGenre;
            return View(listMovie);
        }

        public IActionResult ListMovieByGenres(string name)
        {
            var item = _genreRepository.GetGenreByName(name);
            if(item != null)
            {
                var listMovie = _genreRepository.GetMoviesByGenres(item.idGenre);
                ViewBag.nameGenre = item.nameGenre;
                return View(listMovie);
            }
            return View("ListMovieByGenresNone");
        }

        public IActionResult ListMovieByGenresNone(string name)
        {
            return View();
        }
    }
}

LAMovies_NET6/Controllers/PricingController.cs
using LAMovies_NET6.Interfaces;
using LAMovies_NET6.Models;
using LAMovies_NET6.Models.DTO;
using LAMovies_NET6.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace LAMovies_NET6.Controllers
{
    public class PricingController : Controller
    {
        private readonly IPricingRepository _pricingRepository;
        private readonly IUserAuthRepository _userAuthRepository;

        public PricingController(IPricingRepository pricingRepository, IUserAuthRepository userAuthRepository)
        {
            _pricingRepository = pricingRepository;
            _userAuthRepository = userAuthRepository;
        }
        public IActionResult Pricing()
        {
            var pricing = _pricingRepository.GetAllPricings().ToList();
            return View(pricing);
        }
        public IActionResult PricingNone()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        public IActionResult QLPricing()
        {
            var pricing = _pricingRepository.GetAllPricings().ToList();
            return View(pricing);
        }

        [Authorize(Roles = "admin")]
        public IActionResult AddPricing()
        {
            return View();

        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public IActionResult AddPricing(Pricing model)
        {
                _pricingRepository.Add(model);
                return Redirect("QLPricing");
        }
        [Authorize(Roles = "admin")]
        public IActionResult EditPrice(int id)
        {
            var data = _pricingRepository.GetById(id);
            return View(data);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public IActionResult EditPrice(Pricing model)
        {
            _pricingRepository.Update(model);
            return RedirectToAction(nameof(QLPricing));

        }
        [Authorize(Roles = "admin")]
        public IActionResult DeletePricing(int id)
        {
            var result = _pricingRepository.Delete(id);
            return RedirectToAction(nameof(QLPricing));
        }
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> QLUserPricing()
        {
            var listUserPricing = _pricingRepository.GetAllUserPricings().ToList();
            List<ListUserPricingDTO> list = new List<ListUserPricingDTO> ();
            foreach(var item in listUserPricing)
            {
                var user = await _userAuthRepository.GetAccountById(item.idUser);
                var pricing = await _pricingRepository.GetPricingById(item.idPricing);
                ListUserPricingDTO userPricingDTO = new ListUserPricingDTO()
                {
                    usernameUser = user.UserName,
                    fullNameUser = user.fullName,
                    namePricing = pricing.namePricing,
                    startTime = item.startTime,
                    endTime = item.endTime,
                    remainingTime = item.endTime - DateTime.Now
                };
                list.Add(userPricingDTO);
            }
            return View(list);
        }
    }
}

LAMovies_NET6/Controllers/UserController.cs
using LAMovies_NET6.Interfaces;
using LAMovies_NET6.Models;
using LAMovies_NET6.Models.DTO;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LAMovies_NET6.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserAuthRepository _userAuthRepository;
        private readonly IPricingRepository _pricingRepository;


        public UserController(IUserAuthRepository userAuthRepository, IPricingRepository pricingRepository)
        {
            _userAuthRepository = userAuthRepository;
            _pricingRepository = pricingRepository;
        }
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginDTO model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var result = await _userAuthRepository.LoginAsync(model);
            if (result.statusCode == 2)
            {
                return RedirectToAction("Index", "Home");
            }
            else if(result.statusCode == 1)
            {
                return Redirect("/Home/Dashboard");
            }
            else
            {
                TempData["msg"] = result.message;
                return RedirectToAction(nameof(Login));
            }
        }
        public IActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SignUp(RegistrationDTO model)
        {
            if (!ModelState.IsValid) { return View(model); }
            model.Role = "user";
            var result = await this._userAuthRepository.RegisterAsync(model);
            if (result.statusCode == 1)
            {
                LoginDTO loginDTO = new LoginDTO() { userName = model.userName, password = model.password };
                await Login(loginDTO);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["msg"] = result.message;
                return RedirectToAction(nameof(SignUp));
            }
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await this._userAuthRepository.LogoutAsync();
            await HttpContext.SignOutAsync();
            return RedirectToAction(nameof(Login));
        }

        public IActionResult ErrorLogin()
        {
            return View();
        }
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> DisplayInfoUser()
        {
            var user = await _userAuthRepository.GetInfoAccount();
            return View(user);
        }
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> ChangePassword()
        {
            var user = await _userAuthRepository.GetInfoAccount();
            var checkPasswordDTO = new CheckPasswordDTO()
            {
                 id = user.Id,
                 name = user.fullName,
            };
            return View(checkPasswordDTO);
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> ChangePassword(CheckPasswordDTO checkPasswordDTO)
        {
            if (!ModelState.IsValid) {
                return View(checkPasswordDTO); 
            }
            var result = await _userAuthRepository.UpdatePassword(checkPasswordDTO);
            if (result.statusCode == 1)
            {
                TempData["true"] = result.message;
                return RedirectToAction(nameof(ChangePassword));
            }
            else
            {
                TempData["msg"] = result.message;
                return RedirectToAction(nameof(ChangePassword));
            }
        }
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> EditInfoUser()
        {
            var user = await _userAuthRepository.GetInfoAccount();
            return View(user);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EditInfoUser(User user)
        {
            var result = await _userAuthRepository.Update(user);
            if (result)
            {
                return RedirectToAction(nameof(DisplayInfoUser));
            }
            else
            {
                TempData["msg"] = "Edit Error";
                return View(user);
            }
        }

        [Authorize]
        public async Task<IActionResult> InfoServiceUser()
        {
            var pricing = await _pricingRepository.GetPricingByUser();
            var pricingEx = await _pricingRepository.CheckPricingExpired();
            ViewBag.CheckPricingExpired = pricingEx;
            return View(pricing);
        }
        [Authorize(Roles = "admin")]
        public IActionResult QLAccount()
        {
            var account = _userAuthRepository.GetAllAccount();
            return View(account);
        }
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteAccount(String id)
        {
            var result = await _userAuthRepository.DeleteAccount(id);
            return RedirectToAction(nameof(QLAccount));
        }
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> EditAccount(String id)
        {
            var user = await _userAuthRepository.GetAccountById(id);
            return View(user);
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        public async Task<IActionResult> EditAccount(User user)
        {
            var result = await _userAuthRepository.Update(user);
            if (result)
            {
                return RedirectToAction(nameof(QLAccount));
            }
            else
            {
                TempData["msg"] = "Edit Error";
                return View(user);
            }
        }
    }
}

LAMovies_NET6/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="@Url.Content("~/faviconicon.ico")" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
    <link href="~/assets/css/icons.min.css" rel="stylesheet" />
    <link href="~/assets/css/app-modern.min.css" rel="stylesheet" />
    <title>@ViewData["Title"]</title>

</head>
<body class="loading" data-layout="detached">

    <!-- Topbar Start -->
    <div class="navbar-custom topnav-navbar topnav-navbar-dark">
        <div class="container-fluid">


            <a style="margin-left: 115px" href="/Admin/Admin/Index" class="topnav-logo">
                <span class="topnav-logo-lg">
                    <img src="~/Content/faviconn.ico" alt="" height="50">
                </span>
                <span class="topnav-logo-sm">
                    <img src="~/Content/faviconn.ico" alt="" height="50">
                </span>
            </a>


            <ul class="list-unstyled topbar-menu float-end mb-0">
                <li class="dropdown notification-list">
                    <a class="nav-link dropdown-toggle nav-user arrow-none me-0" data-bs-toggle="dropdown" id="topbar-userdrop" href="#" role="button" aria-haspopup="true"
                       aria-expanded="false">
                        <span class="account-user-avatar">
                            <img src="~/image/avarta/avatar-default.png" alt="user-image" class="rounded-circle">
                        </span>
                        <span>
                            <span class="account-user-name">
                                @User.Identity.Name
                            </span>
                            <span class="account-position">
                                Admin
                            </span>
                        </span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-end dropdown-menu-animated topbar-dropdown-menu profile-dropdown" aria-labelledby="topbar-userdrop">
                        <!-- item-->
                        <div class=" dropdown-header noti-title">
                            <h6 class="text-overflow m-0">Welcome !</h6>
                        </div>

                        <!-- item-->
                        <a asp-action="DisplayInfoUser" asp-controller="User" class="dropdown-item notify-item">
                            <i class="mdi mdi-account-circle me-1"></i>
                            <span>Thông tin cá nhân</span>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <i class="mdi mdi-account-edit me-1"></i>
                            <span>Cài đặt</span>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <i class="mdi mdi-lifebuoy me-1"></i>
                            <span>Hỗ trợ</span>
                        </a>


                        <!-- item-->
                        <a asp-controller="User" asp-action="Logout" class="dropdown-item notify-item">
                            <i class="mdi mdi-logout me-1"></i>
                            <span>Đăng xuất</span>
                        </a>
                    </div>
                </li>
            </ul>
            <a class="button-menu-mobile disable-btn">
                <div class="lines">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </a>

        </div>
    </div>
    <!-- end Topbar -->
    <!-- Start Content-->
    <div class="container-fluid">

        <!-- Begin page -->
        <div class="wrapper">

            <!-- ========== Left Sidebar Start ========== -->
            <div class="leftside-menu leftside-menu-detached">

                <div class="leftbar-user">
                    <a asp-action="DisplayInfoUser" asp-controller="User">
                        <img src="~/image/avarta/avatar-default.png" alt="user-image" height="42" class="rounded-circle shadow-sm">
                        <span class="leftbar-user-name">
                            @User.Identity.Name
                        </span>
                    </a>
                </div>

                <!--- Sidemenu -->
                <ul class="side-nav">

                    <li class="side-nav-title side-nav-item">Navigation</li>

                    <li class="side-nav-item">
                        <a asp-controller="Home" asp-action="Dashboard" class="side-nav-link">
                            <i class="uil-home-alt"></i>
                            <span> Trang chủ </span>
                        </a>
                    </li>

                    <li class="side-nav-item">
                        <a asp-controller="Movies" asp-action="QLMovies" class="side-nav-link">
                            <i class="fa-solid fa-film"></i>
                            <span> Quản lý phim </span>
                        </a>
                    </li>
                    <li class="side-nav-item">
                        <a asp-controller="Genre" asp-action="QLGenres" class="side-nav-link">
                            <i class="uil-tag-alt"></i>
                            <span> Quản lý thể loại </span>
                        </a>
                    </li>
                    <li class="side-nav-item">
                        <a asp-controller="Actor" asp-action="QLActor" class="side-nav-link">
                            <i class="fa-solid fa-user-secret"></i>
                            <span> Quản lý diễn viên </span>
                        </a>
                    </li>
                    <li class="side-nav-item">
                        <a asp-controller="Pricing" asp-action="QLPricing" class="side-nav-link">
                            <i class="fa-brands fa-servicestack"></i>
                            <span> Quản lý dịch vụ </span>
                        </a>
                    </li>
                    <li class="side-nav-item">
                        <a asp-controller="User" asp-action="QLAccount" class="side-nav-link">
                            <i class="uil-users-alt"></i>
                            <span> Quản lý tài khoản </span>
                        </a>
                    </li>
                    <li class="side-nav-item">
                        <a asp-controller="Pricing" asp-action="QLUserPricing" class="side-nav-link">
                            <i class="fa-solid fa-business-time"></i>
                            <span> Quản lý gói cước </span>
                        </a>
                    </li>

                    <!--

                        <li class="side-nav-item">
                        <a href="/Admin/QLVoucher/QLVoucher" class="side-nav-link">
                            <i class="fa-solid fa-gift"></i>
                            <span> Quản lý voucher </span>
                        </a>
                    </li>
                        -->



                </ul>


                <!-- End Sidebar -->

                <div class="clearfix"></div>
                <!-- Sidebar -left -->

            </div>
            <!-- Left Sidebar End -->

            <div class="content-page">
                <div class="content">
                    <!-- start page title -->
                    <!-- end page title -->
                    <div class="row">
                        @RenderBody()
                    </div>
                </div>
            </div>

            <!-- END Container -->
            <!-- bundle -->
            <script src="~/assets/js/vendor.min.js"></script>
            <script src="~/assets/js/app.min.js"></script>

            <!-- third party js -->
            <script src="~/assets/js/vendor/apexcharts.min.js"></script>
            <script src="~/assets/js/vendor/jquery-jvectormap-1.2.2.min.js"></script>
            <script src="~/Content/assets/js/vendor/jquery-jvectormap-world-mill-en.js"></script>
            <!-- third party js ends -->
            <!-- demo app -->
            <script src="~/assets/js/pages/demo.dashboard.js"></script>
            <!-- end demo js-->
            <style>
                a {
                    text-decoration: none !important;
                }
            </style>
            @RenderSection("scripts", required: false)


</body>

</html>

LAMovies_NET6/Views/Shared/_PartialHistory.cshtml
@using LAMovies_NET6.Models.DTO
@using Microsoft.AspNetCore.Http;
@using Newtonsoft.Json;
@{
    var context = ViewContext.HttpContext; // Lấy HttpContext từ ViewContext
    var movieNotifyJson = context.Session.GetString("movieNotify");
}
@if (!string.IsNullOrEmpty(movieNotifyJson))
{
    var Movie = JsonConvert.DeserializeObject<List<HistoryMoviesDTO>>(movieNotifyJson);
    <li class="nav-item nav-icon">
        <a href="#" class="search-toggle position-relative">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="22"
                 height="22" class="noti-svg">
                <path fill="none" d="M0 0h24v24H0z" />
                <path d="M18 10a6 6 0 1 0-12 0v8h12v-8zm2 8.667l.4.533a.5.5 0 0 1-.4.8H4a.5.5 0 0 1-.4-.8l.4-.533V10a8 8 0 1 1 16 0v8.667zM9.5 21h5a2.5 2.5 0 1 1-5 0z" />
            </svg>
            <span class="bg-danger dots"></span>
        </a>
        <div class="iq-sub-dropdown">
            <div class="iq-card shadow-none m-0">
                <div class="iq-card-body">
                    @if (Movie.Count != 0)
                    {
                        @foreach (var item in Movie)
                        {
                            @if (String.Compare(item.typeMovie, "oddMovies", StringComparison.Ordinal) == 0)
                            {
                                <a href="/Movies/WatchMovie?movieId=@item.idMovie" class="iq-sub-card">
                                    <div class="media align-items-center">
                                        <img src="@item.uriImg" class="img-fluid mr-3" width="64px" />
                                        <div class="media-body">
                                            <h6 class="mb-0 ">@item.nameMovie</h6>
                                            @{
                                                TimeSpan remainingTime = item.remainingTime;
                                                string formattedTime;

                                                if (remainingTime.TotalHours < 1)
                                                {
                                                    formattedTime = $"{remainingTime.Minutes} minutes ago";
                                                }
                                                else if (remainingTime.TotalDays < 1)
                                                {
                                                    formattedTime = $"{remainingTime.Hours} hours {remainingTime.Minutes} minutes ago";
                                                }
                                                else
                                                {
                                                    formattedTime = $"{remainingTime.Days} days ago";
                                                }
                                            }
                                            <small class="font-size-12">@formattedTime </small>
                                        </div>
                                    </div>
                                </a>
                            }
                            else
                            {
                                <a href="/Movies/WatchMovieSeries?movieId=@item.idMovie&tap=@item.episodes" class="iq-sub-card">
                                    <div class="media align-items-center">
                                        <img src="@item.uriImg" class="img-fluid mr-3" width="64px" />
                                        <div class="media-body">
                                            <h6 class="mb-0 ">@item.nameMovie</h6>
                                            <small class="font-size-12">Enpisodes @item.episodes </small>
                                            <br>
                                            @{
                                                TimeSpan remainingTime = item.remainingTime;
                                                string formattedTime;

                                                if (remainingTime.TotalHours < 1)
                                                {
                                                    formattedTime = $"{remainingTime.Minutes} minutes ago";
                                                }
                                                else if (remainingTime.TotalDays < 1)
                                                {
                                                    formattedTime = $"{remainingTime.Hours} hours {remainingTime.Minutes} minutes ago";
                                                }
                                                else
                                                {
                                                    formattedTime = $"{remainingTime.Days} days ago";
                                                }
                                            }
                                            <small class="font-size-12">@formattedTime </small>
                                        </div>
                                    </div>
                                </a>
                            }
                        }
                    }
                    else
                    {
                        <a href="#" class="iq-sub-card">
                            <div class="media align-items-center">
                                <div class="media-body">
                                    <h6 class="mb-0 ">You don't have any notifications!!</h6>
                                </div>
                            </div>
                        </a>
                    }
                </div>
            </div>
        </div>
    </li>
}
else
{
}

LAMovies_NET6/Views/Shared/_PartialMoveEpisode.cshtml
@using LAMovies_NET6.Models

@{
    var Movie = TempData["movieLink"] as List<SeriesMovie>;
    var tap = ViewBag.totalTap;
    int i = 0;
}

@foreach (var item in Movie)
{
    i++;
    <a href="/Movies/WatchMovieSeries?movieId=@item.idMovie&tap=@item.practice" class="active btn btn-outline-danger m-2">Episode @item.practice</a>
}
@if(i == tap)
{
    <div class="ganre-wrapper pt-3">
        Episode:
        <a href="#">
            Full @i/@tap
        </a>
    </div>
}
else
{
    <div class="ganre-wrapper pt-3">
        Episode:
        <a href="#">
            Update @i/@tap
        </a>
    </div>
}

LAMovies_NET6/Views/Shared/_PartialMoviesGenres.cshtml
@using LAMovies_NET6.Models
@{
    var Movie = ViewBag.moviesGenres;
}

@if (Movie != null)
{
    @foreach (var item in Movie)
    {
        <li class="slide-item">
            <div class="block-images position-relative">
                <div class="img-box">
                    <img src="@item.uriImgCover" class="img-fluid" alt="">
                </div>
                <div class="block-description">
                    <h6 class="iq-title"><a href="movie-details.html">@item.nameMovie</a></h6>
                    <div class="movie-time d-flex align-items-center my-2">
                        <div class="badge-hd badge-danger p-1 mr-2">@item.qualityMovie</div>
                        <div class="badge badge-secondary p-1 mr-2">@item.minAgeMovie +</div>
                        <span class="text-white">@item.timeMovie</span>
                    </div>
                    <div class="hover-buttons text-center">
                        <span class="btn btn-danger iq-button" onclick="window.location.href='/Movies/MovieDetail?movieId=@item.idMovie'">
                            <i class="fa-solid fa-circle-info"></i>
                            More Details
                        </span>
                        <a href="@item.uriMovieTrailer" class="video-open btn btn-danger iq-button ml-2">
                            <i class="fa-solid fa-tv"></i>
                            Trailer
                        </a>
                    </div>
                </div>
            </div>
        </li>
    }
}